--
-- PostgreSQL database dump
--



-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

-- Started on 2026-03-24 20:14:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5185 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16390)
-- Name: Account_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Account_states" (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public."Account_states" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16397)
-- Name: App_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."App_users" (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    street_number character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    postal_code character(5) NOT NULL,
    country character varying(255) NOT NULL,
    last_connection timestamp(0) without time zone NOT NULL,
    account_state_id integer NOT NULL,
    account_creation_date timestamp(0) without time zone NOT NULL,
    deletion_date date
);


ALTER TABLE public."App_users" OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16709)
-- Name: App_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."App_users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."App_users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16411)
-- Name: Budget_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Budget_states" (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public."Budget_states" OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16733)
-- Name: budgets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.budgets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.budgets_id_seq OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16418)
-- Name: Budgets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Budgets" (
    id bigint DEFAULT nextval('public.budgets_id_seq'::regclass) NOT NULL,
    job_id bigint NOT NULL,
    agreed_price double precision NOT NULL,
    budget_state_id integer NOT NULL,
    creation_date timestamp(0) without time zone NOT NULL
);


ALTER TABLE public."Budgets" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16426)
-- Name: Chats; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Chats" (
    id bigint NOT NULL,
    task_id bigint CONSTRAINT "Chats_job_id_not_null" NOT NULL,
    professional_id bigint NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public."Chats" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16433)
-- Name: Client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Client" (
    id bigint NOT NULL,
    app_user_id bigint NOT NULL
);


ALTER TABLE public."Client" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16706)
-- Name: Client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Client" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Client_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16438)
-- Name: Invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invoices" (
    id bigint NOT NULL,
    task_id bigint CONSTRAINT "Invoices_job_id_not_null" NOT NULL,
    total_payment double precision NOT NULL,
    app_comission double precision NOT NULL,
    professional_revenue double precision NOT NULL,
    payment_method character varying(255) NOT NULL,
    payment_date date NOT NULL
);


ALTER TABLE public."Invoices" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16448)
-- Name: Messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Messages" (
    id bigint NOT NULL,
    chat_id bigint NOT NULL,
    sent_by bigint NOT NULL,
    recived_by bigint NOT NULL,
    text character varying(255) NOT NULL,
    message_date timestamp(0) without time zone NOT NULL
);


ALTER TABLE public."Messages" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16457)
-- Name: Professional; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Professional" (
    id bigint NOT NULL,
    app_user_id bigint NOT NULL
);


ALTER TABLE public."Professional" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16711)
-- Name: Professional_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Professional" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Professional_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16462)
-- Name: Professional_profession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Professional_profession" (
    professional_id bigint NOT NULL,
    profession_id integer NOT NULL
);


ALTER TABLE public."Professional_profession" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16467)
-- Name: Professions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Professions" (
    id integer NOT NULL,
    name_profession character varying(255) NOT NULL,
    min_price double precision NOT NULL
);


ALTER TABLE public."Professions" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16473)
-- Name: Report_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Report_states" (
    id integer NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public."Report_states" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16480)
-- Name: Reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Reports" (
    id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    reportee_id bigint NOT NULL,
    report_origin character varying(255) NOT NULL,
    cause character varying(255) NOT NULL,
    report_state_id integer NOT NULL
);


ALTER TABLE public."Reports" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16491)
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16496)
-- Name: Task_states; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Task_states" (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public."Task_states" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16501)
-- Name: Tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tasks" (
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    professional_id bigint NOT NULL,
    profession_id integer NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    photo_1 bytea,
    photo_2 bytea,
    video_1 bytea,
    video_2 bytea,
    task_state_id integer NOT NULL,
    token_qr character varying(255) NOT NULL,
    creation_date timestamp(0) without time zone NOT NULL,
    accorded_date date,
    accorded_time time(0) without time zone,
    review_to_client character varying(255),
    score_to_client integer,
    review_to_professional character varying(255),
    score_to_professional integer
);


ALTER TABLE public."Tasks" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 16730)
-- Name: Tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tasks" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tasks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16525)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    id bigint NOT NULL,
    rol_id integer NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    dni character(20) NOT NULL,
    email character varying(255) NOT NULL,
    mobile character varying(20),
    birthdate date,
    password character varying(255) NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16705)
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16683)
-- Name: migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.migrations (
    id integer NOT NULL,
    migration character varying(255) NOT NULL,
    batch integer NOT NULL
);


ALTER TABLE public.migrations OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16682)
-- Name: migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.migrations_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.migrations_id_seq OWNER TO postgres;

--
-- TOC entry 5186 (class 0 OID 0)
-- Dependencies: 236
-- Name: migrations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.migrations_id_seq OWNED BY public.migrations.id;


--
-- TOC entry 243 (class 1259 OID 16713)
-- Name: personal_access_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personal_access_tokens (
    id bigint NOT NULL,
    tokenable_type character varying(255) NOT NULL,
    tokenable_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    token character varying(64) NOT NULL,
    abilities text,
    last_used_at timestamp without time zone,
    expires_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.personal_access_tokens OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16712)
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.personal_access_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.personal_access_tokens_id_seq OWNER TO postgres;

--
-- TOC entry 5187 (class 0 OID 0)
-- Dependencies: 242
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.personal_access_tokens_id_seq OWNED BY public.personal_access_tokens.id;


--
-- TOC entry 4936 (class 2604 OID 16686)
-- Name: migrations id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations ALTER COLUMN id SET DEFAULT nextval('public.migrations_id_seq'::regclass);


--
-- TOC entry 4937 (class 2604 OID 16716)
-- Name: personal_access_tokens id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_access_tokens ALTER COLUMN id SET DEFAULT nextval('public.personal_access_tokens_id_seq'::regclass);


--
-- TOC entry 5153 (class 0 OID 16390)
-- Dependencies: 219
-- Data for Name: Account_states; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Account_states" (id, name) FROM stdin;
1	active
2	banned
3	pending aprobation
4	in revision
5	inactive
6	deleted
\.


--
-- TOC entry 5154 (class 0 OID 16397)
-- Dependencies: 220
-- Data for Name: App_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."App_users" (id, user_id, street_number, city, postal_code, country, last_connection, account_state_id, account_creation_date, deletion_date) FROM stdin;
201	101	Calle Mayor 1	Madrid	28001	España	2026-02-03 19:09:04	1	2026-02-03 19:09:04	\N
202	102	Av. Diagonal 200	Barcelona	08001	España	2026-02-03 19:09:04	1	2026-02-03 19:09:04	\N
3	5	Calle Mayor 5	Madrid	28001	España	2026-03-03 19:04:39	1	2026-03-03 19:04:39	\N
17	19	Calle Herreros 12	Valencia	46001	España	2026-03-09 19:10:42	1	2026-03-09 19:10:42	\N
18	20	Calle Mayor 10	Madrid	28001	España	2026-03-16 18:07:30	1	2026-03-16 18:07:30	\N
19	101	Calle Falsa 123	Madrid	28001	España	2026-03-23 18:56:16	1	2026-03-23 18:56:16	\N
20	23	Calle de la Fe 7	Barcelona	08001	España	2026-03-23 18:48:03	1	2026-03-23 18:48:03	\N
21	24	Avenida del Vidrio 10	Barcelona	08002	España	2026-03-23 18:51:22	1	2026-03-23 18:51:22	\N
\.


--
-- TOC entry 5155 (class 0 OID 16411)
-- Dependencies: 221
-- Data for Name: Budget_states; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Budget_states" (id, name) FROM stdin;
1	pending
2	accepted
3	rejected
4	modified insitu
\.


--
-- TOC entry 5156 (class 0 OID 16418)
-- Dependencies: 222
-- Data for Name: Budgets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Budgets" (id, job_id, agreed_price, budget_state_id, creation_date) FROM stdin;
1	8	65.5	2	2026-03-23 19:00:42
\.


--
-- TOC entry 5157 (class 0 OID 16426)
-- Dependencies: 223
-- Data for Name: Chats; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Chats" (id, task_id, professional_id, client_id) FROM stdin;
\.


--
-- TOC entry 5158 (class 0 OID 16433)
-- Dependencies: 224
-- Data for Name: Client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Client" (id, app_user_id) FROM stdin;
301	201
1	3
2	19
3	20
\.


--
-- TOC entry 5159 (class 0 OID 16438)
-- Dependencies: 225
-- Data for Name: Invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Invoices" (id, task_id, total_payment, app_comission, professional_revenue, payment_method, payment_date) FROM stdin;
\.


--
-- TOC entry 5160 (class 0 OID 16448)
-- Dependencies: 226
-- Data for Name: Messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Messages" (id, chat_id, sent_by, recived_by, text, message_date) FROM stdin;
\.


--
-- TOC entry 5161 (class 0 OID 16457)
-- Dependencies: 227
-- Data for Name: Professional; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Professional" (id, app_user_id) FROM stdin;
9	17
10	18
11	21
\.


--
-- TOC entry 5162 (class 0 OID 16462)
-- Dependencies: 228
-- Data for Name: Professional_profession; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Professional_profession" (professional_id, profession_id) FROM stdin;
9	1
9	3
10	10
11	4
\.


--
-- TOC entry 5163 (class 0 OID 16467)
-- Dependencies: 229
-- Data for Name: Professions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Professions" (id, name_profession, min_price) FROM stdin;
1	Fontanero	15
2	Cerrajero	25
3	Técnico de Calderas	20
4	Cristalero	20
5	Téc. Electrodomésticos	15
6	Manitas (Handyman)	15
7	Carpintero	15
8	Pintor	15
9	Albañil	15
10	Parquetista	15
11	Tapicero	15
12	Limpieza Hogar	15
13	Jardinero	15
14	Fumigador	30
15	Electricista	30
16	Mudanzas y Portes	30
\.


--
-- TOC entry 5164 (class 0 OID 16473)
-- Dependencies: 230
-- Data for Name: Report_states; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Report_states" (id, name) FROM stdin;
1	Pendiente
\.


--
-- TOC entry 5165 (class 0 OID 16480)
-- Dependencies: 231
-- Data for Name: Reports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Reports" (id, reporter_id, reportee_id, report_origin, cause, report_state_id) FROM stdin;
1001	201	202	Chat	Comportamiento inadecuado	1
\.


--
-- TOC entry 5166 (class 0 OID 16491)
-- Dependencies: 232
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Roles" (id, name) FROM stdin;
1	CLIENTE
2	PROFESIONAL
3	ADMIN
4	SUPER_ADMIN
\.


--
-- TOC entry 5167 (class 0 OID 16496)
-- Dependencies: 233
-- Data for Name: Task_states; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Task_states" (id, name) FROM stdin;
1	solicited
2	negotiating
3	in process
4	accepted
5	finalized
6	cancelled
7	expired
\.


--
-- TOC entry 5168 (class 0 OID 16501)
-- Dependencies: 234
-- Data for Name: Tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tasks" (id, client_id, professional_id, profession_id, title, description, photo_1, photo_2, video_1, video_2, task_state_id, token_qr, creation_date, accorded_date, accorded_time, review_to_client, score_to_client, review_to_professional, score_to_professional) FROM stdin;
4	301	9	1	Fuga de agua en la cocina	El grifo no para de gotear desde ayer.	\N	\N	\N	\N	1	sQPomY7xjikDWQlLXeJx	2026-03-17 18:02:38	\N	\N	\N	\N	\N	\N
7	301	9	1	Fuga de agua en la cocina	El grifo no para de gotear desde ayer.	\\x646174613a696d6167652f706e673b6261736536342c6956424f5277304b47676f414141414e5355684555674141414145414141414243415941414141664663534a4141414144556c4551565234326d50387a3842514477414568514741684b6d4d495141414141424a52553545726b4a6767673d3d	\N	\N	\N	1	3uRePKpFLP6ypa5nVWEd	2026-03-17 19:05:18	\N	\N	\N	\N	\N	\N
8	3	11	4	Restauración Virgen María de cristal	Hola Edith. Limpiando la ventana se me ha caído una figura de cristal muy especial de la Virgen María y se le ha roto el manto. ¿Podrías arreglarla y dejarla como nueva?	\N	\N	\N	\N	2	vXjuEMvqjLxuccsx4gn0	2026-03-23 18:54:37	\N	\N	\N	\N	\N	\N
\.


--
-- TOC entry 5169 (class 0 OID 16525)
-- Dependencies: 235
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" (id, rol_id, name, surname, dni, email, mobile, birthdate, password) FROM stdin;
101	1	Juan	Ejemplo	11111111A           	cliente@ejemplohandly.com	600111222	1990-01-01	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
102	2	Ana	Pro	22222222B           	ana@ejemplohandly.com	600333444	1985-05-20	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
103	3	Carlos	Administrador	33333333C           	admin@handly.com	600500500	1985-03-15	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
104	4	Laura	Jefa Suprema	44444444D           	superadmin@handly.com	600900900	1982-07-20	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
5	1	Maria	Pruebas	99999999Z           	maria@prueba.com	600999888	1995-08-15	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
19	2	Pepe	El Manitas	77777777H           	pepe@manitas.com	600333444	1985-11-20	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
20	2	Roberto	Reformas	55555555R           	roberto@reformas.com	600777888	1988-03-15	$2y$12$5v3hJhYnYhy6Jwffr6XegeXuPIRGy4YLXcJ69vFjbH9uXbNaL1lC.
23	1	Ledys	Ventanas	12345678L           	ledys@ejemplo.com	\N	\N	$2y$12$aNVRN9R.t7bnl6Z7bFbyueSTY6E/MULp0nOEdPeCxhJMBu7GF8nsi
24	2	Edith	Cristales	87654321E           	edith@ejemplo.com	\N	\N	$2y$12$IM1C8.49bd7YrXasgM2tVeOk.yFqItVqLo6J2op4uhzKB.W1rx8QO
\.


--
-- TOC entry 5171 (class 0 OID 16683)
-- Dependencies: 237
-- Data for Name: migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.migrations (id, migration, batch) FROM stdin;
\.


--
-- TOC entry 5177 (class 0 OID 16713)
-- Dependencies: 243
-- Data for Name: personal_access_tokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.personal_access_tokens (id, tokenable_type, tokenable_id, name, token, abilities, last_used_at, expires_at, created_at, updated_at) FROM stdin;
1	App\\Models\\User	5	auth_token	7e9a25aebe7b3a6746c31d27c21e88e48a03f0194c68b3d170ba1e7ed5f211ff	["*"]	2026-03-09 18:29:44	\N	2026-03-09 18:17:21	2026-03-09 18:29:44
2	App\\Models\\User	5	auth_token	159cddfa3cd91f3927aa228e9cc1bede1eea9345d08f862fe2d12be6f8c9c697	["*"]	\N	\N	2026-03-09 18:52:05	2026-03-09 18:52:05
9	App\\Models\\User	101	auth_token	9f5ba2516cefb8df16bae54026d1865dabfb5d2bb1735c8917749137558a0cb8	["*"]	2026-03-17 19:05:18	\N	2026-03-17 18:58:37	2026-03-17 19:05:18
10	App\\Models\\User	101	auth_token	cd1411cc325b35f434619d3fb02b125792b72fcf461c64e2621d93983f630e9d	["*"]	2026-03-23 17:56:34	\N	2026-03-23 17:52:57	2026-03-23 17:56:34
11	App\\Models\\User	101	auth_token	8aa56b182e199402ed3e2ffb04daad97b2a1ff7b7f77ce65a4a1b70c50e9ed24	["*"]	2026-03-23 18:00:47	\N	2026-03-23 17:56:37	2026-03-23 18:00:47
12	App\\Models\\User	101	auth_token	a30f9341560d070926274bd80f7804cc0e09a165064218073c215fe467368b83	["*"]	2026-03-23 18:24:59	\N	2026-03-23 18:03:14	2026-03-23 18:24:59
4	App\\Models\\User	101	auth_token	592802241b3757b120b74d32a6fa746da8f261cbf42bbe9e1c837f3f05d23ecd	["*"]	2026-03-17 18:07:17	\N	2026-03-17 17:53:11	2026-03-17 18:07:17
5	App\\Models\\User	101	auth_token	ddcc793fcd4490c9faf90309ccfd7bfe10f50d99fd2e5d1a008a60e53b59a76c	["*"]	2026-03-17 18:15:24	\N	2026-03-17 18:14:27	2026-03-17 18:15:24
6	App\\Models\\User	20	auth_token	eaa484e2f541c0e08c592f579df0d191ac7be2fc754a28851cc9e1405b135bfc	["*"]	2026-03-17 18:22:11	\N	2026-03-17 18:21:25	2026-03-17 18:22:11
13	App\\Models\\User	20	auth_token	b16cf0e78c3ca939ab0f4d09fc61ea3b41fd112acc75569bfaa514a6bb19ff2a	["*"]	2026-03-23 18:35:55	\N	2026-03-23 18:32:16	2026-03-23 18:35:55
7	App\\Models\\User	101	auth_token	1961a6640dcf8436eadf09f8cc617212ecdffeed708d9e6a697b3b8dde75a5bc	["*"]	2026-03-17 18:30:02	\N	2026-03-17 18:27:50	2026-03-17 18:30:02
14	App\\Models\\User	23	auth_token	4e74e608db34deef3ce28536e0eb734c0bfcfce0703a9b33d45275ac03795ce3	["*"]	2026-03-23 18:54:37	\N	2026-03-23 18:50:11	2026-03-23 18:54:37
8	App\\Models\\User	20	auth_token	163a1efe1e3390640669e60438234372cf4abed35ceb43c7b2b5bb521584aec7	["*"]	2026-03-17 18:49:17	\N	2026-03-17 18:30:46	2026-03-17 18:49:17
15	App\\Models\\User	24	auth_token	6485c1c083a237e05976386dd50a465c243fae646fdab2eddcfde451cb62a30b	["*"]	2026-03-23 19:00:42	\N	2026-03-23 18:55:51	2026-03-23 19:00:42
16	App\\Models\\User	23	auth_token	1c2cd2e7eb571251dac33a10a62e0e529d0411ba4b305809f6a0c94f6cf993e4	["*"]	2026-03-23 19:04:04	\N	2026-03-23 19:02:06	2026-03-23 19:04:04
\.


--
-- TOC entry 5188 (class 0 OID 0)
-- Dependencies: 240
-- Name: App_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."App_users_id_seq"', 21, true);


--
-- TOC entry 5189 (class 0 OID 0)
-- Dependencies: 239
-- Name: Client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Client_id_seq"', 3, true);


--
-- TOC entry 5190 (class 0 OID 0)
-- Dependencies: 241
-- Name: Professional_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Professional_id_seq"', 11, true);


--
-- TOC entry 5191 (class 0 OID 0)
-- Dependencies: 244
-- Name: Tasks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tasks_id_seq"', 8, true);


--
-- TOC entry 5192 (class 0 OID 0)
-- Dependencies: 238
-- Name: Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_id_seq"', 24, true);


--
-- TOC entry 5193 (class 0 OID 0)
-- Dependencies: 245
-- Name: budgets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.budgets_id_seq', 1, true);


--
-- TOC entry 5194 (class 0 OID 0)
-- Dependencies: 236
-- Name: migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.migrations_id_seq', 1, false);


--
-- TOC entry 5195 (class 0 OID 0)
-- Dependencies: 242
-- Name: personal_access_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.personal_access_tokens_id_seq', 16, true);


--
-- TOC entry 4939 (class 2606 OID 16540)
-- Name: Account_states Account_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Account_states"
    ADD CONSTRAINT "Account_states_pkey" PRIMARY KEY (id);


--
-- TOC entry 4941 (class 2606 OID 16542)
-- Name: App_users App_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."App_users"
    ADD CONSTRAINT "App_users_pkey" PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 16544)
-- Name: Budget_states Budget_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Budget_states"
    ADD CONSTRAINT "Budget_states_pkey" PRIMARY KEY (id);


--
-- TOC entry 4946 (class 2606 OID 16546)
-- Name: Budgets Budgets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Budgets"
    ADD CONSTRAINT "Budgets_pkey" PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 16548)
-- Name: Chats Chats_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Chats"
    ADD CONSTRAINT "Chats_pkey" PRIMARY KEY (id);


--
-- TOC entry 4951 (class 2606 OID 16550)
-- Name: Client Client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "Client_pkey" PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 16552)
-- Name: Invoices Invoices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "Invoices_pkey" PRIMARY KEY (id);


--
-- TOC entry 4955 (class 2606 OID 16554)
-- Name: Messages Messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "Messages_pkey" PRIMARY KEY (id);


--
-- TOC entry 4957 (class 2606 OID 16556)
-- Name: Professional Professional_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professional"
    ADD CONSTRAINT "Professional_pkey" PRIMARY KEY (id);


--
-- TOC entry 4959 (class 2606 OID 16729)
-- Name: Professional_profession Professional_profession_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professional_profession"
    ADD CONSTRAINT "Professional_profession_pkey" PRIMARY KEY (professional_id, profession_id);


--
-- TOC entry 4961 (class 2606 OID 16560)
-- Name: Professions Professions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professions"
    ADD CONSTRAINT "Professions_pkey" PRIMARY KEY (id);


--
-- TOC entry 4963 (class 2606 OID 16562)
-- Name: Report_states Report_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Report_states"
    ADD CONSTRAINT "Report_states_pkey" PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 16564)
-- Name: Reports Reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT "Reports_pkey" PRIMARY KEY (id);


--
-- TOC entry 4968 (class 2606 OID 16566)
-- Name: Roles Roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "Roles_pkey" PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 16568)
-- Name: Task_states Task_states_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Task_states"
    ADD CONSTRAINT "Task_states_pkey" PRIMARY KEY (id);


--
-- TOC entry 4972 (class 2606 OID 16570)
-- Name: Tasks Tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT "Tasks_pkey" PRIMARY KEY (id);


--
-- TOC entry 4976 (class 2606 OID 16572)
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- TOC entry 4982 (class 2606 OID 16691)
-- Name: migrations migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4984 (class 2606 OID 16725)
-- Name: personal_access_tokens personal_access_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 4986 (class 2606 OID 16727)
-- Name: personal_access_tokens personal_access_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_token_key UNIQUE (token);


--
-- TOC entry 4974 (class 2606 OID 16574)
-- Name: Tasks tasks_token_qr_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT tasks_token_qr_unique UNIQUE (token_qr);


--
-- TOC entry 4978 (class 2606 OID 16576)
-- Name: Users users_dni_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_dni_unique UNIQUE (dni);


--
-- TOC entry 4980 (class 2606 OID 16578)
-- Name: Users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 4942 (class 1259 OID 16579)
-- Name: fki_app_users_state_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_app_users_state_id ON public."App_users" USING btree (account_state_id);


--
-- TOC entry 4947 (class 1259 OID 16580)
-- Name: fki_budgets_budget_state_foreign; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_budgets_budget_state_foreign ON public."Budgets" USING btree (budget_state_id);


--
-- TOC entry 4966 (class 1259 OID 16581)
-- Name: fki_reports_state_report_states_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_reports_state_report_states_id ON public."Reports" USING btree (report_state_id);


--
-- TOC entry 4987 (class 2606 OID 16582)
-- Name: App_users app_users_state_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."App_users"
    ADD CONSTRAINT app_users_state_id FOREIGN KEY (account_state_id) REFERENCES public."Account_states"(id);


--
-- TOC entry 4988 (class 2606 OID 16587)
-- Name: App_users app_users_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."App_users"
    ADD CONSTRAINT app_users_user_id_foreign FOREIGN KEY (user_id) REFERENCES public."Users"(id);


--
-- TOC entry 4989 (class 2606 OID 16592)
-- Name: Budgets budgets_budget_state_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Budgets"
    ADD CONSTRAINT budgets_budget_state_foreign FOREIGN KEY (budget_state_id) REFERENCES public."Budget_states"(id);


--
-- TOC entry 4990 (class 2606 OID 16597)
-- Name: Budgets budgets_job_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Budgets"
    ADD CONSTRAINT budgets_job_id_foreign FOREIGN KEY (job_id) REFERENCES public."Tasks"(id);


--
-- TOC entry 4991 (class 2606 OID 16602)
-- Name: Chats chats_client_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Chats"
    ADD CONSTRAINT chats_client_id_foreign FOREIGN KEY (client_id) REFERENCES public."Client"(id);


--
-- TOC entry 4992 (class 2606 OID 16607)
-- Name: Chats chats_professional_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Chats"
    ADD CONSTRAINT chats_professional_id_foreign FOREIGN KEY (professional_id) REFERENCES public."Professional"(id);


--
-- TOC entry 4993 (class 2606 OID 16612)
-- Name: Chats chats_task_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Chats"
    ADD CONSTRAINT chats_task_id_foreign FOREIGN KEY (task_id) REFERENCES public."Tasks"(id);


--
-- TOC entry 4994 (class 2606 OID 16617)
-- Name: Client client_app_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT client_app_user_id_foreign FOREIGN KEY (app_user_id) REFERENCES public."App_users"(id);


--
-- TOC entry 4995 (class 2606 OID 16622)
-- Name: Invoices invoices_task_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT invoices_task_id_foreign FOREIGN KEY (task_id) REFERENCES public."Tasks"(id);


--
-- TOC entry 4996 (class 2606 OID 16627)
-- Name: Messages messages_chat_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT messages_chat_id_foreign FOREIGN KEY (chat_id) REFERENCES public."Chats"(id);


--
-- TOC entry 4997 (class 2606 OID 16632)
-- Name: Professional professional_app_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professional"
    ADD CONSTRAINT professional_app_user_id_foreign FOREIGN KEY (app_user_id) REFERENCES public."App_users"(id);


--
-- TOC entry 4998 (class 2606 OID 16642)
-- Name: Professional_profession professional_profession_profession_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professional_profession"
    ADD CONSTRAINT professional_profession_profession_id_foreign FOREIGN KEY (profession_id) REFERENCES public."Professions"(id);


--
-- TOC entry 4999 (class 2606 OID 16647)
-- Name: Reports reports_reportee_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT reports_reportee_id_foreign FOREIGN KEY (reportee_id) REFERENCES public."App_users"(id);


--
-- TOC entry 5000 (class 2606 OID 16652)
-- Name: Reports reports_reporter_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT reports_reporter_id_foreign FOREIGN KEY (reporter_id) REFERENCES public."App_users"(id);


--
-- TOC entry 5001 (class 2606 OID 16657)
-- Name: Reports reports_state_report_states_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Reports"
    ADD CONSTRAINT reports_state_report_states_id FOREIGN KEY (report_state_id) REFERENCES public."Report_states"(id);


--
-- TOC entry 5002 (class 2606 OID 16662)
-- Name: Tasks tasks_client_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT tasks_client_id_foreign FOREIGN KEY (client_id) REFERENCES public."Client"(id);


--
-- TOC entry 5003 (class 2606 OID 16667)
-- Name: Tasks tasks_professional_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT tasks_professional_id_foreign FOREIGN KEY (professional_id) REFERENCES public."Professional"(id);


--
-- TOC entry 5004 (class 2606 OID 16672)
-- Name: Tasks tasks_task_state_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tasks"
    ADD CONSTRAINT tasks_task_state_id_foreign FOREIGN KEY (task_state_id) REFERENCES public."Task_states"(id);


--
-- TOC entry 5005 (class 2606 OID 16677)
-- Name: Users users_rol_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT users_rol_id_foreign FOREIGN KEY (rol_id) REFERENCES public."Roles"(id);


-- Completed on 2026-03-24 20:14:38

--
-- PostgreSQL database dump complete
--


